name: "release-tauri-app"

on:
  push:
    branches:
      - update-0.5.5
  workflow_dispatch:

jobs:
  create-release:
    permissions: write-all
    environment: Relay Release
    runs-on: ubuntu-latest
    outputs:
      releaseId: ${{ steps.step1.outputs.id }}
    steps:
      - id: step1
        uses: ncipollo/release-action@v1
        with:
          tag: v0.9.70
          name: "Volla Messages ${{ github.ref_name }}"
          body: |
            See the assets to download this version and install.

            Android builds are distinguished as either 'rich' or 'lite':
            - The 'rich' build includes a bundled holochain conductor. It can be used on any Android device.
            - The 'lite' build relies on the holochain conductor provided by the [Android Service Runtime app](https://github.com/holochain/android-service-runtime). The Android Service Runtime app can be installed on any Android device, and will be preinstalled with Volla OS.
          prerelease: false
          draft: false

  release-tauri-app-linux:
    needs: create-release
    permissions: write-all
    environment: Relay Release
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x86_64
            runner: ubuntu-22.04
            target: x86_64-unknown-linux-gnu
          - arch: aarch64
            runner: ubuntu-22.04-arm
            target: aarch64-unknown-linux-gnu
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.target }}

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: stable

      - name: Install Linux deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libsoup-3.0-dev \
            libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev \
            pkg-config
          # Only pin WebKitGTK on amd64
          if [ "${{ matrix.arch }}" = "x86_64" ]; then
              mkdir -p /tmp/ubuntu-packages
              cd /tmp/ubuntu-packages
              wget https://launchpadlibrarian.net/723972773/libwebkit2gtk-4.1-0_2.44.0-0ubuntu0.22.04.1_amd64.deb
              wget https://launchpadlibrarian.net/723972761/libwebkit2gtk-4.1-dev_2.44.0-0ubuntu0.22.04.1_amd64.deb
              wget https://launchpadlibrarian.net/723972770/libjavascriptcoregtk-4.1-0_2.44.0-0ubuntu0.22.04.1_amd64.deb
              wget https://launchpadlibrarian.net/723972746/libjavascriptcoregtk-4.1-dev_2.44.0-0ubuntu0.22.04.1_amd64.deb
              wget https://launchpadlibrarian.net/723972735/gir1.2-javascriptcoregtk-4.1_2.44.0-0ubuntu0.22.04.1_amd64.deb
              wget https://launchpadlibrarian.net/723972739/gir1.2-webkit2-4.1_2.44.0-0ubuntu0.22.04.1_amd64.deb
              wget https://launchpadlibrarian.net/606433947/libicu70_70.1-2ubuntu1_amd64.deb
              wget https://launchpadlibrarian.net/606433941/libicu-dev_70.1-2ubuntu1_amd64.deb
              wget https://launchpadlibrarian.net/606433945/icu-devtools_70.1-2ubuntu1_amd64.deb
              wget https://launchpadlibrarian.net/595623693/libjpeg8_8c-2ubuntu10_amd64.deb
              wget https://launchpadlibrarian.net/587202140/libjpeg-turbo8_2.1.2-0ubuntu1_amd64.deb
              wget https://launchpadlibrarian.net/592959859/xdg-desktop-portal-gtk_1.14.0-1build1_amd64.deb
              sudo apt-get install -y /tmp/ubuntu-packages/*.deb
          fi

      - name: Install and prepare
        run: |
          npm install
          npm run setup:happ-release

      - name: Copy tauri config (desktop)
        run: cp -f src-tauri/tauri.desktop.conf.json src-tauri/tauri.conf.json

      - name: Build App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.create-release.outputs.releaseId }}
          args: --verbose --features holochain_bundled --target ${{ matrix.target }}

  release-tauri-app-android:
    permissions: write-all
    environment: Relay Release
    needs: 
      - release-tauri-app-linux
      - create-release
    runs-on: ubuntu-22.04 
    strategy:
      fail-fast: false
      matrix:
        include:
          - feature: 'holochain_service'
            label: lite
          - feature: 'holochain_bundled'
            label: rich
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
      - name: Install Android SDK
        uses: android-actions/setup-android@v3
      - name: Install dependencies
        run: npm install
      - name: Copy tauri config for android
        run: cp -f src-tauri/tauri.android.conf.json src-tauri/tauri.conf.json
      - name: Build Android App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.create-release.outputs.releaseId }}
          args: --verbose --features ${{ matrix.feature }}

  release-tauri-app-windows:
    needs: create-release
    permissions: write-all
    environment: Relay Release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install dependencies
        run: npm install
      - name: Copy tauri config for windows
        run: cp src-tauri/tauri.windows.conf.json src-tauri/tauri.conf.json
      - name: Build Windows App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.create-release.outputs.releaseId }}
          args: --verbose --features holochain_bundled

  release-tauri-app-macos:
    needs: create-release
    permissions: write-all
    environment: Relay Release
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: macos-latest
            args: '--target aarch64-apple-darwin'
          - platform: macos-latest
            args: '--target x86_64-apple-darwin'
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.13
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install dependencies
        run: npm install
      - name: Copy tauri config for macos
        run: cp src-tauri/tauri.macos.conf.json src-tauri/tauri.conf.json
      - name: Build macOS App
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.create-release.outputs.releaseId }}
          args: --verbose --features holochain_bundled ${{ matrix.args }}
